### ISSUE TITLE
Not possible to mention people in jenkins notification message

### ISSUE THREAD

**Issue by sruthicps** [jenkinsci/office-365-connector-plugin#181] opened 2019-11-19 07:05 UTC
Using the following code to send notification message to MS Teams.
`office365ConnectorSend message: 'This is a sample notification', status: currentBuild.result, webhookUrl: "https://outlook.office.com/webhook/24340149-02xxxxxxxxxx"
`
it would be nice if there is an option for mentioning people in notification message. For example '@developers'

**Comment by damianszczepanik** [comment] 2019-11-28 22:56
Duplicate of #179

**Closed by damianszczepanik** 2019-11-28 22:56 UTC
