### ISSUE TITLE
Build Name Setter changes not reflected after updating in build environment before build.

### ISSUE THREAD

**Issue by scubadam** [jenkinsci/office-365-connector-plugin#45] opened 2017-11-22 13:10 UTC
Jenkins allows you to modify the build name using Build Name Setter plugin. I had hoped that in doing so this would be reflected in the Build name used for the card posted to the webhook. Sadly it looks like the name is taken from the run right at the beginning and not updated, even if it appears modified in Jenkins before the build starts the Connector plugin doesn't see this change. This is odd as even notifications after the build finishes are affected. I guess the connector is initialised at the beginning and the values never re-loaded. Could they be?
Another option would be to optionally add some Build Parameters to the facts because in part it is these parameters that help distinguish our builds and the name wouldn't matter so much if we could see certain build params. (Obviously not all as some could be large and unwieldy in a card in teams)
Thanks

**Comment by casz** [comment] 2017-11-22 13:28
>>This is odd as even notifications after the build finishes are affected. 

Could you clarify this?
so the notification that comes after the build is finished, has the updated build name?

**Comment by scubadam** [comment] 2017-11-22 13:47
Sorry I mean 'affected by the issue' , so a notification for success after the build doesn't represent the build name that is set in the job or that i see in jenkins. All I meant by this comment is that I could see a notification for build starting not having the correct name set as it might happen before the env is set up. However I couldn't understand a success/failure notification after the build completes still using the same name.

**Comment by damianszczepanik** [comment] 2017-11-22 20:09
I believe this is duplicate of #10 - should be fixed with next release.

**Comment by casz** [comment] 2017-11-22 20:13
#10 will solve this, yes.

Here is why:
https://github.com/jenkinsci/build-name-setter-plugin/blob/5a576c40707aaf4c8e53829485421169eafe3e67/src/main/java/org/jenkinsci/plugins/buildnamesetter/BuildNameSetter.java#L76 :)

**Comment by damianszczepanik** [comment] 2018-01-11 20:37
Then, this issue can be closed

**Comment by themakshter** [comment] 2018-01-26 17:07
#10 does not fix the issue because it gets the display name of the parents, which I would think would be the job name itself. Our use case is when each individual build/run of a jenkins job has a different display name. So essentially when we want to also include `run.getDisplayName()` if `run.hasCustomDisplayName` in our `activitySubtitle`.

**Comment by damianszczepanik** [comment] 2018-01-26 23:34
Can you share more details about configuration of such job so then we can confirm the issue and verify the fix?

**Comment by casz** [comment] 2018-01-28 13:12
#53 should fix both multibranch use case and satisfies those using custom DisplayName for a run.

**Comment by themakshter** [comment] 2018-01-28 20:45
@damianszczepanik we use a single parameterised Jenkins job to deploy our boxes - that job is just called `deploy`. It takes in a box name and build branch as parameters and then changes the display name of that job run to be a combination of branch and box name. For example, a run for `BOX-B` for `master` branch would be `#35-master-BOX-B`. However, the team card we would receive would still only show that it was `build 35` for job `deploy` and we would not know which box or branch it was.

**Comment by themakshter** [comment] 2018-01-28 20:52
Thank you @casz 

Could you explain to me how to verify the hpi artifact? I am not sure how to do it. But I looked at the code and the tests created for it as well. If they pass, I think this should work.

**Comment by casz** [comment] 2018-01-28 20:55
@themakshter Manage Jenkins > Manage Plugins > Advanced > Upload Plugin
https://jenkins.io/doc/book/managing/plugins/#from-the-web-ui-2

**Comment by themakshter** [comment] 2018-03-09 16:20
Apologies for the late reply but I have tested this artifact and can confirm that this works as expected,

**Closed** 2018-04-13 03:51 UTC
